language: python
dist: xenial
sudo: required
cache:
- apt
addons:
  apt:
     sources:
       - sourceline: "deb https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/p/powershell/ xenial main"
         key_url: "https://packages.microsoft.com/keys/microsoft.asc"
     packages:
     - nginx
     - curl
     - wget
script:
- bash -x test.sh
